name = "Fantasy Pack"
author = "kaii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69de9452791dba7c9dfc843ea51b4910fbf120676df10987a744571c17b9a59a"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
