name = "Fantasy Pack"
author = "kaii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3ee6776424c2d2ef0adf674511b759de48086dae3ba728bf601943d7c61a72d"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
